# Generated by Django 5.2.7 on 2025-10-08 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Draft', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_phase', models.CharField(choices=[('ban1', 'Ban Phase 1'), ('pick1', 'Pick Phase 1'), ('ban2', 'Ban Phase 2'), ('pick2', 'Pick Phase 2'), ('ban3', 'Ban Phase 3'), ('pick3', 'Pick Phase 3'), ('completed', 'Draft Completed')], default='ban1', max_length=20)),
                ('current_turn', models.CharField(default='blue', max_length=10)),
                ('is_completed', models.BooleanField(default=False)),
                ('session_key', models.CharField(blank=True, max_length=50, null=True)),
                ('turn_order', models.JSONField(default=list)),
                ('current_turn_index', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DraftNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draft_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='mlbb_web.draftsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DraftTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('session_key', models.CharField(blank=True, max_length=50, null=True)),
                ('blue_picks', models.JSONField(default=list)),
                ('red_picks', models.JSONField(default=list)),
                ('blue_bans', models.JSONField(default=list)),
                ('red_bans', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('blue', 'Blue Side'), ('red', 'Red Side')], max_length=10)),
                ('name', models.CharField(default='Team', max_length=50)),
                ('draft_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='mlbb_web.draftsession')),
            ],
            options={
                'unique_together': {('draft_session', 'side')},
            },
        ),
        migrations.CreateModel(
            name='HeroPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_id', models.IntegerField()),
                ('hero_name', models.CharField(max_length=50)),
                ('position', models.IntegerField(blank=True, choices=[(1, 'Exp Lane'), (2, 'Jungler'), (3, 'Mid Lane'), (4, 'Gold Lane'), (5, 'Roamer')], null=True)),
                ('pick_order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='mlbb_web.team')),
            ],
            options={
                'ordering': ['pick_order'],
                'unique_together': {('team', 'pick_order')},
            },
        ),
        migrations.CreateModel(
            name='HeroBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_id', models.IntegerField()),
                ('hero_name', models.CharField(max_length=50)),
                ('ban_order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to='mlbb_web.team')),
            ],
            options={
                'ordering': ['ban_order'],
                'unique_together': {('team', 'ban_order')},
            },
        ),
    ]
